name: JSONPrettifier CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install dependencies
      run: |
        cd backend
        go mod tidy
        
    - name: Run tests
      run: |
        cd backend
        go test ./...
        
    - name: Build
      run: |
        cd backend
        go build -v ./cmd/server
  
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    # Uncomment when you have tests for the frontend
    # - name: Run tests
    #   run: npm test
  
  deploy:
    name: Deploy
    needs: [test-backend, test-frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v3
    
    # Example deployment step - customize based on your hosting provider
    - name: Deploy to production
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here
        # For example:
        # - Deploy to AWS, Heroku, Netlify, etc.
        # - Use specific deployment actions from the GitHub Marketplace
    
    - name: Notify deployment
      run: |
        echo "Deployment completed!" 